name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - uses: actions/checkout@v3

      # 安装 Wrangler
      - name: Install Wrangler
        run: npm install -g wrangler

      # 部署 Worker
      - name: Deploy Worker
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npx wrangler deploy